name: Containerized Webman

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t webman-app .
          
      - name: Run tests in container
        run: |
          docker run -d -p 8787:8787 webman-app
          sleep 5
          curl -s http://127.0.0.1:8787 | grep "Webman"
